# Generated by Django 4.2.5 on 2023-10-21 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_mail', models.EmailField(max_length=150, verbose_name='контактный Email')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ф.И.О.')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='коментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='тема письма')),
                ('text', models.TextField(blank=True, null=True, verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_send', models.TimeField(verbose_name='время рассылки')),
                ('periodicity', models.CharField(choices=[('daily', 'раз в день'), ('weekly', 'раз в неделю'), ('monthly', 'раз в месяц')], max_length=50, verbose_name='переодичность')),
                ('status_code', models.CharField(choices=[('create', 'создана'), ('active', 'запущена'), ('finish', 'завершена')], default='create', max_length=50, verbose_name='статус рассылки')),
                ('next_send', models.DateField(verbose_name='дата следующей отправки')),
                ('client_id', models.ManyToManyField(to='mailing.clients', verbose_name='клиенты')),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='Сообщения')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField()),
                ('server_request', models.CharField(max_length=200)),
                ('mailings_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing')),
            ],
        ),
    ]
