# Generated by Django 4.2.5 on 2023-09-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='contact_mail',
            field=models.EmailField(max_length=150, verbose_name='контактный Email'),
        ),
    ]
