# Generated by Django 4.2.5 on 2023-10-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_clients_user_logs_user_mailing_user_message_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'verbose_name': 'лог', 'verbose_name_plural': 'логи'},
        ),
        migrations.RenameField(
            model_name='logs',
            old_name='server_request',
            new_name='server_response',
        ),
    ]
