# Generated by Django 4.2.5 on 2023-10-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='коментарий'),
        ),
    ]
