# Generated by Django 4.2.5 on 2023-10-17 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_clients_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_send', models.TimeField(verbose_name='время рассылки')),
                ('periodicity', models.CharField(choices=[('day', 'раз в день'), ('week', 'раз в неделю'), ('month', 'раз в месяц')], max_length=50, verbose_name='переодичность')),
                ('status_code', models.CharField(choices=[('active', 'запущена'), ('closed', 'завершена')], default='создана', max_length=50, verbose_name='статус рассылки')),
                ('next_send', models.DateField()),
                ('client_id', models.ManyToManyField(to='mailing.clients')),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.message')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField()),
                ('server_request', models.CharField(max_length=200)),
                ('mailings_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing')),
            ],
        ),
    ]
