# Generated by Django 4.2.5 on 2023-10-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='сщдержимое статьи')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='изображение')),
                ('view_count', models.IntegerField(default=0, verbose_name='количество просмотров')),
                ('date_publish', models.DateField(auto_now=True, verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
            },
        ),
    ]
